### PR TITLE
[FEATURE] Load data from composer.json if present

### PR DESCRIPTION
**Pull request by linawolf**
Load data like description, support links, composer name etc from the composer.json if one is found.

### CODE REVIEW

**Review by jaapio — CHANGES_REQUESTED** [review]
I would opt for a more generic solution for this feature. If we would pass the projectNode in an event, we could attach any listener to the project node to add extra variables.  

By doing this the run command doesn't have to be aware of the listeners that are part of building step of the project node. And there would be no need to change the Settings as they are just used to transfer the data to the project node? 

If there is a reason to have the composer information in the settings, I would suggest to create a more generic format to store them in the settings. Right now the settings object is really specify changed for the composer addition. And if we have more of these kind of topic it would be grow fast.

**Comment by linawolf** [comment]
How, when and where would you pass the project node?

**Comment by linawolf** [comment]
@jaapio how can we proceed?

**Comment by jaapio** [comment]
> How, when and where would you pass the project node?

I would trigger in event just like you do right now in the run command. Something like `ProjectLoaded` which includes the project node.

**Comment by linawolf** [comment]
@jaapio please have another look if this is what you intended

**Review by jaapio — APPROVED** [review]

**Comment by jaapio** [comment]
@linawolf can you please have a look at the merge conflicts?

**Pull request merged**
