### PR TITLE
Chore/phpstan strict

### PR DESCRIPTION
**Pull request by jaapio**
Clean up of the code:

- use static for static methods in phpunit
- remove some dead code
- cleanup generic logic in rules.

### CODE REVIEW

**Comment by linawolf** [comment]
Could we wait with them until we have the big PRs merged? Otherwise we will have conflict hell

**Comment by jaapio** [comment]
Yes, I will keep this up to date :-)

**Review by linawolf — APPROVED** [review]
I think this looks good

**Comment by linawolf** [comment]
Please resolve conflicts before merging

**Pull request merged**
