### PR TITLE
[FEATURE] Create a rst theme to render markdown

### PR DESCRIPTION
**Pull request by linawolf**

### CODE REVIEW

**Comment by linawolf** [comment]
@jaapio any chance you could help me here?

**Comment by jaapio** [comment]
@linawolf I pushed a small addition to make your part working. You were missing something in the configuration of the new supported output format. I think when looking into this there is room for improvement. But it seems to work right now. I didn't look into the templates yet. But the changes I did are now used when rendering the output

**Comment by linawolf** [comment]
@jaapio I can somehow not get psalm to work. Could you have a look please?

**Comment by jaapio** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.x|[](https://github.com/phpDocumentor/guides/pull/1152)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
