### PR TITLE
 Run Bootstrap Theme as Application

### PR DESCRIPTION
**Pull request by linawolf**
Not sure if this is the best way to go.

### CODE REVIEW

**Comment by wouterj** [comment]
I think we should only keep one application (`guides-cli`) and add extension support to it. Themes would then ship an `Extension` PHP class that configures a theme in the DI container.

In a CLI option (or config file), a user can then specify which theme it wants. Something like:

```php

class ThemeManager
{
    private array $themeMap = [];

    public function __construct(
        private \Twig\Loader\FilesystemLoader $loader,
        private array $defaultPaths
    ) {
    }

    public function registerTheme(string $name, array $paths)
    {
        $this->themeMap[$name] = $paths;
    }

    public function useTheme(string $name)
    {
        $this->loader->setPaths(array_merge($this->defaultPaths, $this->themeMap[$name] ?? []));
    }
}
```

**Comment by linawolf** [comment]
That sounds like a better idea, however I don't really know how to build it :(

**Comment by wouterj** [comment]
Yeah, the concrete implementation is also not 100% clear in my head. In https://github.com/phpDocumentor/guides/pull/333 , I'm trying to get extensions working that we can then apply for the bootstrap theme. I'll keep you posted on that experiment :)

**Comment by linawolf** [comment]
I will work on the ThemeManager idea

**Pull request closed without merging**
